# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Ator',
                'verbose_name_plural': 'Atores',
            },
        ),
        migrations.CreateModel(
            name='AtoresFilme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playtv.Ator')),
            ],
            options={
                'verbose_name': 'Ator do filme',
                'verbose_name_plural': 'Atores do filme',
            },
        ),
        migrations.CreateModel(
            name='AtoresSeriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playtv.Ator')),
            ],
            options={
                'verbose_name': 'Ator do seriado',
                'verbose_name_plural': 'Atores do seriado',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True)),
                ('titulo_ingles', models.CharField(max_length=50, unique=True)),
                ('imagem', models.URLField(max_length=500, verbose_name=b'Endere\xc3\xa7o para miniatura')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='CategoriasFilme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playtv.Categoria')),
            ],
            options={
                'verbose_name': 'Categoria do filme',
                'verbose_name_plural': 'Categorias do filme',
            },
        ),
        migrations.CreateModel(
            name='CategoriasSeriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playtv.Categoria')),
            ],
            options={
                'verbose_name': 'Categoria do seriado',
                'verbose_name_plural': 'Categorias do seriado',
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('episodio', models.SmallIntegerField(default=1)),
                ('temporada', models.SmallIntegerField(default=1)),
                ('status_execucao', models.SmallIntegerField(choices=[(0, b'PARADO'), (1, b'REPRODUZINDO'), (2, b'PAUSADO')], default=0)),
                ('carga_automatica', models.BooleanField(default=False, verbose_name=b'Carga automatica')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name=b'Data de cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name=b'Data de ultima atualizacao')),
            ],
            options={
                'verbose_name': 'Episodio seriado',
                'verbose_name_plural': 'Episodios seriado',
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True)),
                ('titulo_ingles', models.CharField(max_length=50, unique=True)),
                ('sinopse', models.TextField(verbose_name=b'Sinopse/Enredo')),
                ('imagem', models.URLField(max_length=500, verbose_name=b'Endere\xc3\xa7o para miniatura')),
                ('status_execucao', models.SmallIntegerField(choices=[(0, b'PARADO'), (1, b'REPRODUZINDO'), (2, b'PAUSADO')], default=0)),
                ('carga_automatica', models.BooleanField(default=False, verbose_name=b'Carga automatica')),
                ('classificacao_imdb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('votos_imdb', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tipo', models.CharField(default=b'movie', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name=b'Data de cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name=b'Data de ultima atualizacao')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
            },
        ),
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500)),
                ('detalhe', models.CharField(max_length=200)),
                ('importacao_concluida', models.BooleanField(default=False)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name=b'Data de ultima atualizacao')),
            ],
            options={
                'verbose_name': 'Importacao',
                'verbose_name_plural': 'Importacoes',
            },
        ),
        migrations.CreateModel(
            name='LinksEpisodioSeriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500)),
                ('qualidade', models.CharField(choices=[(b'480p', b'HDTV'), (b'720p', b'HD'), (b'1080p', b'FULLHD')], default=b'720p', max_length=5)),
                ('dublado', models.BooleanField(default=True)),
                ('fonte', models.SmallIntegerField(choices=[(0, b'INTERNET'), (1, b'YOUTUBE')], default=0)),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playtv.Episodio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinksFilme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500)),
                ('qualidade', models.CharField(choices=[(b'480p', b'HDTV'), (b'720p', b'HD'), (b'1080p', b'FULLHD')], default=b'720p', max_length=5)),
                ('dublado', models.BooleanField(default=True)),
                ('fonte', models.SmallIntegerField(choices=[(0, b'INTERNET'), (1, b'YOUTUBE')], default=0)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playtv.Filme')),
            ],
            options={
                'verbose_name': 'Link para assistir o filme',
                'verbose_name_plural': 'Links do filme',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500)),
                ('detalhe', models.CharField(max_length=200)),
                ('status_execucao', models.SmallIntegerField(choices=[(0, b'PARADO'), (1, b'REPRODUZINDO'), (2, b'PAUSADO')], default=0)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name=b'Data de ultima atualizacao')),
            ],
            options={
                'verbose_name': 'Tocando',
                'verbose_name_plural': 'Tocando',
            },
        ),
        migrations.CreateModel(
            name='Seriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True)),
                ('sinopse', models.TextField(verbose_name=b'Sinopse/Enredo')),
                ('imagem', models.URLField(max_length=500, verbose_name=b'Endere\xc3\xa7o para miniatura')),
                ('carga_automatica', models.BooleanField(default=False, verbose_name=b'Carga automatica')),
                ('classificacao_imdb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('votos_imdb', models.DecimalField(decimal_places=3, max_digits=10, verbose_name=b'Quantidade de votos no imdb')),
                ('tipo', models.CharField(default=b'series', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name=b'Data de cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name=b'Data de ultima atualizacao')),
            ],
            options={
                'verbose_name': 'Seriado',
                'verbose_name_plural': 'Seriados',
            },
        ),
        migrations.AddField(
            model_name='episodio',
            name='seriado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playtv.Seriado'),
        ),
        migrations.AddField(
            model_name='categoriasseriado',
            name='seriado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playtv.Seriado'),
        ),
        migrations.AddField(
            model_name='categoriasfilme',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playtv.Filme'),
        ),
        migrations.AddField(
            model_name='atoresseriado',
            name='seriado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playtv.Seriado'),
        ),
        migrations.AddField(
            model_name='atoresfilme',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playtv.Filme'),
        ),
    ]
