# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playtv', '0003_auto_20160214_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksepisodioseriado',
            name='legenda',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linksfilme',
            name='legenda',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
