# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playtv', '0004_auto_20160214_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execucao',
            old_name='endereco_ip',
            new_name='endereco_ip_solicitante',
        ),
        migrations.RenameField(
            model_name='execucao',
            old_name='nome_maquina',
            new_name='ip_executando',
        ),
        migrations.AddField(
            model_name='execucao',
            name='nome_maquina_solicitante',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='execucao',
            name='porta_executando',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episodio',
            name='status_execucao',
            field=models.SmallIntegerField(choices=[(0, b'PARADO'), (1, b'REPRODUZINDO'), (2, b'PAUSADO'), (3, b'STREAM')], default=0),
        ),
        migrations.AlterField(
            model_name='filme',
            name='status_execucao',
            field=models.SmallIntegerField(choices=[(0, b'PARADO'), (1, b'REPRODUZINDO'), (2, b'PAUSADO'), (3, b'STREAM')], default=0),
        ),
    ]
