# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playtv', '0006_auto_20160214_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucao',
            name='porta_executando',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
