# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playtv', '0007_auto_20160215_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucao',
            name='status_execucao',
            field=models.SmallIntegerField(choices=[(0, b'PARADO'), (1, b'REPRODUZINDO'), (2, b'PAUSADO'), (3, b'STREAM')], default=0),
        ),
    ]
